import { Device } from "@/interfaces/user/layout/layoutBodyPrep";

export const demoData: { devices: Device[] } = {
  devices: [
    {
      id: "batch_ball_mill_1",
      type: "BatchBaalMill",
      status: "blue",
      lightsConfig: { orientation: "horizontal", position: "top" },
      current: "35A",
    },
    {
      id: "batch_ball_mill_2",
      type: "BatchBaalMill",
      status: "red",
      lightsConfig: { orientation: "horizontal", position: "top" },
      startTime: "04:00:00",
    },
    {
      id: "batch_ball_mill_3",
      type: "BatchBaalMill",
      status: "grey",
      lightsConfig: { orientation: "horizontal", position: "top" },
      startTime: "01:20:47",
    },
    {
      id: "batch_ball_mill_4",
      type: "BatchBaalMill",
      status: "blue",
      lightsConfig: { orientation: "horizontal", position: "top" },
      current: "38A",
    },
    {
      id: "spray_dryer",
      type: "SprayDryer",
      status: "red",
      lightsConfig: { orientation: "horizontal", position: "center" },
      startTime: "03:30:00",
    },
    {
      id: "slurry_pump_1",
      type: "SlurryPump",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "top" },
      current: "40A",
    },
    {
      id: "slurry_pump_2",
      type: "SlurryPump",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "top" },
      startTime: "00:45:30",
    },
    {
      id: "slurry_pump_3",
      type: "SlurryPump",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "top" },
      startTime: "02:15:00",
    },
    {
      id: "slurry_pit_right_1",
      type: "SlurryPitRight",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "right" },
      current: "42A",
    },
    {
      id: "slurry_pit_right_2",
      type: "SlurryPitRight",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "01:45:00",
    },
    {
      id: "slurry_pit_right_3",
      type: "SlurryPitRight",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "02:10:15",
    },
    {
      id: "slurry_pit_right_4",
      type: "SlurryPitRight",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "right" },
      current: "37A",
    },
    {
      id: "slurry_pit_right_5",
      type: "SlurryPitRight",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "05:00:00",
    },
    {
      id: "slurry_pit_left_1",
      type: "SlurryPitLeft",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      current: "39A",
    },
    {
      id: "slurry_pit_left_2",
      type: "SlurryPitLeft",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "left" },
      startTime: "02:30:00",
    },
    {
      id: "slurry_pit_left_3",
      type: "SlurryPitLeft",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "left" },
      startTime: "00:30:00",
    },
    {
      id: "slurry_pit_left_4",
      type: "SlurryPitLeft",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "left" },
      startTime: "01:00:00",
    },
    {
      id: "slurry_pit_left_5",
      type: "SlurryPitLeft",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      current: "41A",
    },
    {
      id: "continues_ball_mill_1",
      type: "ContinuesBallMill",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "left" },
      startTime: "03:15:20",
    },
    {
      id: "continues_ball_mill_2",
      type: "ContinuesBallMill",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "right" },
      current: "45A",
    },
    {
      id: "vibrating_screen_1",
      type: "VibratingScreen",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "top" },
      startTime: "01:30:00",
    },
    {
      id: "vibrating_screen_2",
      type: "VibratingScreen",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "top" },
      current: "36A",
    },
    {
      id: "vibrating_screen_3",
      type: "VibratingScreen",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "top" },
      startTime: "00:50:10",
    },
    {
      id: "vibrating_screen_4",
      type: "VibratingScreen",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "top" },
      startTime: "02:45:00",
    },
    {
      id: "vibrating_screen_5",
      type: "VibratingScreen",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "top" },
      current: "43A",
    },
    {
      id: "vibrating_screen_6",
      type: "VibratingScreen",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "top" },
      startTime: "01:40:25",
    },
    {
      id: "granule_sillo_1",
      type: "GranuleSillo",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      current: "47A",
    },
    {
      id: "granule_sillo_2",
      type: "GranuleSillo",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "left" },
      startTime: "03:00:00",
    },
    {
      id: "granule_sillo_3",
      type: "GranuleSillo",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "left" },
      startTime: "02:25:45",
    },
    {
      id: "granule_sillo_4",
      type: "GranuleSillo",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      current: "44A",
    },
    {
      id: "granule_sillo_5",
      type: "GranuleSillo",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "left" },
      startTime: "01:15:00",
    },
    {
      id: "granule_sillo_6",
      type: "GranuleSillo",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "left" },
      startTime: "00:15:55",
    },
    {
      id: "granule_sillo_7",
      type: "GranuleSillo",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "right" },
      current: "46A",
    },
    {
      id: "granule_sillo_8",
      type: "GranuleSillo",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "02:00:00",
    },
    {
      id: "granule_sillo_9",
      type: "GranuleSillo",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "01:55:30",
    },
    {
      id: "granule_sillo_10",
      type: "GranuleSillo",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "03:45:00",
    },
    {
      id: "granule_sillo_11",
      type: "GranuleSillo",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "04:30:00",
    },
    {
      id: "granule_sillo_12",
      type: "GranuleSillo",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "00:35:40",
    },
  ],
};