import { Device } from "@/interfaces/user/layout/layoutBodyPrep";
import { getRandomSoilSurface, getRandomTemperature } from "@/utils/homeless/randomGenerator";

export const demoData: { devices: Device[] } = {
  devices: [
    {
      id: "batch_ball_mill_1",
      name: "بالمیل 1",
      type: "BatchBaalMill",
      status: "blue",
      lightsConfig: { orientation: "horizontal", position: "top" },
      extraTooltip: "احتماب خرابی بلبرینگ",

    },
    {
      id: "batch_ball_mill_2",
      name: "بالمیل 2",
      type: "BatchBaalMill",
      status: "red",
      lightsConfig: { orientation: "horizontal", position: "top" },
      startTime: "04:00:00",
    },
    {
      id: "batch_ball_mill_3",
      name: "بالمیل 3",
      type: "BatchBaalMill",
      status: "grey",
      lightsConfig: { orientation: "horizontal", position: "top" },
      startTime: "01:20:47",
    },
    {
      id: "batch_ball_mill_4",
      name: "بالمیل 4",
      type: "BatchBaalMill",
      status: "blue",
      lightsConfig: { orientation: "horizontal", position: "top" },
      temprature: getRandomTemperature(),
    },
    {
      id: "spray_dryer",
      name: "اسپری درایر",
      type: "SprayDryer",
      status: "blue",
      lightsConfig: { orientation: "horizontal", position: "center" },
      current: "96A",
      temprature: getRandomTemperature(),
    },
    {
      id: "slurry_pump_1",
      name: "پمپ 1",
      type: "SlurryPump",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "top" },
      current: "40A",
      temprature: getRandomTemperature(),
    },
    {
      id: "slurry_pump_2",
      name: "پمپ 2",
      type: "SlurryPump",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "top" },
      startTime: "00:45:30",
    },
    {
      id: "slurry_pump_3",
      name: "پمپ 3",
      type: "SlurryPump",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "top" },
      startTime: "02:15:00",
    },
    {
      id: "slurry_pit_right_1",
      name: "حوضچه 1",
      type: "SlurryPitRight",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "right" },
      current: "42A",
      temprature: getRandomTemperature(),
    },
    {
      id: "slurry_pit_right_2",
      name: "حوضچه 2",
      type: "SlurryPitRight",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "01:45:00",
    },
    {
      id: "slurry_pit_right_3",
      name: "حوضچه 3",
      type: "SlurryPitRight",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "02:10:15",
    },
    {
      id: "slurry_pit_right_4",
      name: "حوضچه 4",
      type: "SlurryPitRight",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "right" },
      current: "37A",
      temprature: getRandomTemperature(),
    },
    {
      id: "slurry_pit_right_5",
      name: "حوضچه 5",
      type: "SlurryPitRight",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "05:00:00",
    },
    {
      id: "slurry_pit_left_1",
      name: "حوضچه 1",
      type: "SlurryPitLeft",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      current: "39A",
      temprature: getRandomTemperature(),
      extraTooltip: "احتماب خرابی پره"
    },
    {
      id: "slurry_pit_left_2",
      name: "حوضچه 2",
      type: "SlurryPitLeft",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "left" },
      startTime: "02:30:00",
    },
    {
      id: "slurry_pit_left_3",
      name: "حوضچه 3",
      type: "SlurryPitLeft",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "left" },
      startTime: "00:30:00",
    },
    {
      id: "slurry_pit_left_4",
      name: "حوضچه 4",
      type: "SlurryPitLeft",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "left" },
      startTime: "01:00:00",
    },
    {
      id: "slurry_pit_left_5",
      name: "حوضچه 5",
      type: "SlurryPitLeft",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      current: "41A",
      temprature: getRandomTemperature(),
    },
    {
      id: "continues_ball_mill_1",
      name: "بالمیل 1",
      type: "ContinuesBallMill",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      current: "50A",
      temprature: getRandomTemperature(),
    },
    {
      id: "continues_ball_mill_2",
      name: "بالمیل 2",
      type: "ContinuesBallMill",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "right" },
      current: "45A",
      temprature: getRandomTemperature(),
    },
    {
      id: "vibrating_screen_1",
      name: "صفحه 1",
      type: "VibratingScreen",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "top" },
      startTime: "01:30:00",
    },
    {
      id: "vibrating_screen_2",
      name: "صفحه 2",
      type: "VibratingScreen",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "top" },
      current: "36A",
      temprature: getRandomTemperature(),
    },
    {
      id: "vibrating_screen_3",
      name: "صفحه 3",
      type: "VibratingScreen",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "top" },
      startTime: "00:50:10",
    },
    {
      id: "vibrating_screen_4",
      name: "صفحه 4",
      type: "VibratingScreen",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "top" },
      startTime: "02:45:00",
    },
    {
      id: "vibrating_screen_5",
      name: "صفحه 5",
      type: "VibratingScreen",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "top" },
      current: "43A",
      temprature: getRandomTemperature(),
    },
    {
      id: "vibrating_screen_6",
      name: "صفحه 6",
      type: "VibratingScreen",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "top" },
      startTime: "01:40:25",
    },
    {
      id: "granule_sillo_1",
      type: "GranuleSillo",
      name: "سیلو 1",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      defaultParams: {
        current: "22A",
        soilSurface: getRandomSoilSurface(),
      },
    },
    {
      id: "granule_sillo_2",
      name: "سیلو 2",
      type: "GranuleSillo",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      defaultParams: {
        current: "69A",
        soilSurface: getRandomSoilSurface(),
      },
    },
    {
      id: "granule_sillo_3",
      name: "سیلو 3",
      type: "GranuleSillo",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      defaultParams: {
        current: "61A",
        soilSurface: getRandomSoilSurface(),
      },
    },
    {
      id: "granule_sillo_4",
      name: "سیلو 4",
      type: "GranuleSillo",
      status: "none",
      lightsConfig: { orientation: "vertical", position: "left" },
    },
    {
      id: "granule_sillo_5",
      name: "سیلو 5",
      type: "GranuleSillo",
      status: "none",
      lightsConfig: { orientation: "vertical", position: "left" },
    },
    {
      id: "granule_sillo_6",
      name: "سیلو 6",
      type: "GranuleSillo",
      status: "none",
      lightsConfig: { orientation: "vertical", position: "left" },
    },
    {
      id: "granule_sillo_7",
      name: "سیلو 7",
      type: "GranuleSillo",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "01:30:00",
    },
    {
      id: "granule_sillo_8",
      name: "سیلو 8",
      type: "GranuleSillo",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "02:00:00",
    },
    {
      id: "granule_sillo_9",
      name: "سیلو 9",
      type: "GranuleSillo",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "01:55:30",
    },
    {
      id: "granule_sillo_10",
      name: "سیلو 10",
      type: "GranuleSillo",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "03:45:00",
    },
    {
      id: "granule_sillo_11",
      name: "سیلو 11",
      type: "GranuleSillo",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "00:45:00",
    },
    {
      id: "granule_sillo_12",
      name: "سیلو 12",
      type: "GranuleSillo",
      status: "none",
      lightsConfig: { orientation: "vertical", position: "right" },
    },
  ],
};
