import { Device } from "@/interfaces/user/layout/layoutBodyPrep";
import { getRandomBurnerTemperature, getRandomCurrent, getRandomFlowRate, getRandomWeightSoilEnteringbatchMill, getRandomWeightIncomingWaterMilliliters, getRandomOutletTemperature, getRandomOutputGranuleMoisture, getRandomOutputGranuleTemperature, getRandomOutputGranuleWeight, getRandomOutputSoilWeight, getRandomSoilSurface, getRandomTemperature, getRandomWeightIncomingSoil } from "@/utils/homeless/randomStaticGenerator";

export const demoData: { devices: Device[] } = {
  devices: [
    {
      id: "batch_ball_mill_1",
      name: "بالمیل 1",
      type: "BatchBaalMill",
      status: "blue",
      lightsConfig: { orientation: "horizontal", position: "top" },
      extraTooltip: "احتمال خرابی بلبرینگ",
      operatingTime: "02:15:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
        WeightSoilEnteringbatchMill: getRandomWeightSoilEnteringbatchMill(),
        WeightIncomingWaterMilliliters: getRandomWeightIncomingWaterMilliliters(),
      },
    },
    {
      id: "batch_ball_mill_2",
      name: "بالمیل 2",
      type: "BatchBaalMill",
      status: "red",
      lightsConfig: { orientation: "horizontal", position: "top" },
      startTime: "04:00:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
        WeightSoilEnteringbatchMill: getRandomWeightSoilEnteringbatchMill(),
        WeightIncomingWaterMilliliters: getRandomWeightIncomingWaterMilliliters(),
      },
    },
    {
      id: "batch_ball_mill_3",
      name: "بالمیل 3",
      type: "BatchBaalMill",
      status: "grey",
      lightsConfig: { orientation: "horizontal", position: "top" },
      startTime: "01:20:47",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
        WeightSoilEnteringbatchMill: getRandomWeightSoilEnteringbatchMill(),
        WeightIncomingWaterMilliliters: getRandomWeightIncomingWaterMilliliters(),
      },
    },
    {
      id: "batch_ball_mill_4",
      name: "بالمیل 4",
      type: "BatchBaalMill",
      status: "blue",
      lightsConfig: { orientation: "horizontal", position: "top" },
      operatingTime: "05:43:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
        WeightSoilEnteringbatchMill: getRandomWeightSoilEnteringbatchMill(),
        WeightIncomingWaterMilliliters: getRandomWeightIncomingWaterMilliliters(),
      },
    },
    {
      id: "spray_dryer",
      name: "اسپری درایر",
      type: "SprayDryer",
      status: "blue",
      lightsConfig: { orientation: "horizontal", position: "center" },
      operatingTime: "03:28:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
        BurnerTemperature: getRandomBurnerTemperature(),
        OutletTemperature: getRandomOutletTemperature(),
        OutputGranuleWeight: getRandomOutputGranuleWeight(),
        OutputGranuleTemperature: getRandomOutputGranuleTemperature(),
        OutputGranuleMoisture: getRandomOutputGranuleMoisture(),
      },
    },
    {
      id: "slurry_pump_1",
      name: "پمپ 1",
      type: "SlurryPump",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "top" },
      operatingTime: "06:12:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
        FlowRate: getRandomFlowRate()
      },
    },
    {
      id: "slurry_pump_2",
      name: "پمپ 2",
      type: "SlurryPump",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "top" },
      startTime: "00:45:30",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
        FlowRate: getRandomFlowRate()
      },
    },
    {
      id: "slurry_pump_3",
      name: "پمپ 3",
      type: "SlurryPump",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "top" },
      startTime: "02:15:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
        FlowRate: getRandomFlowRate()
      },
    },
    {
      id: "slurry_pit_right_1",
      name: "حوضچه 1",
      type: "SlurryPitRight",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "right" },
      operatingTime: "04:22:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "slurry_pit_right_2",
      name: "حوضچه 2",
      type: "SlurryPitRight",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "01:45:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "slurry_pit_right_3",
      name: "حوضچه 3",
      type: "SlurryPitRight",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "right" },
      startTime: "02:10:15",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "slurry_pit_right_4",
      name: "حوضچه 4",
      type: "SlurryPitRight",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "right" },
      operatingTime: "06:07:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "slurry_pit_right_5",
      name: "حوضچه 5",
      type: "SlurryPitRight",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "right" },
      operatingTime: "01:53:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "slurry_pit_left_1",
      name: "حوضچه 1",
      type: "SlurryPitLeft",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      extraTooltip: "احتمال خرابی پره",
      operatingTime: "02:34:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "slurry_pit_left_2",
      name: "حوضچه 2",
      type: "SlurryPitLeft",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "left" },
      startTime: "02:30:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "slurry_pit_left_3",
      name: "حوضچه 3",
      type: "SlurryPitLeft",
      status: "grey",
      lightsConfig: { orientation: "vertical", position: "left" },
      startTime: "00:30:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "slurry_pit_left_4",
      name: "حوضچه 4",
      type: "SlurryPitLeft",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      operatingTime: "03:05:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "slurry_pit_left_5",
      name: "حوضچه 5",
      type: "SlurryPitLeft",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      operatingTime: "05:48:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "continues_ball_mill_1",
      name: "بالمیل 1",
      type: "ContinuesBallMill",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      operatingTime: "01:59:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
        WeightIncomingSoil: getRandomWeightIncomingSoil(),
        OutputSoilWeight: getRandomOutputSoilWeight(),
      },
    },
    {
      id: "continues_ball_mill_2",
      name: "بالمیل 2",
      type: "ContinuesBallMill",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "right" },
      operatingTime: "06:40:00",
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
        WeightIncomingSoil: getRandomWeightIncomingSoil(),
        OutputSoilWeight: getRandomOutputSoilWeight(),
      },
    },
    {
      id: "vibrating_screen_1",
      name: "صفحه 1",
      type: "VibratingScreen",
      status: "red",
      lightsConfig: { orientation: "vertical", position: "top" },
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "vibrating_screen_2",
      name: "صفحه 2",
      type: "VibratingScreen",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "top" },
      operatingTime: "03:31:00",
      defaultParams: {
        current: "36A",
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "vibrating_screen_3",
      name: "صفحه 3",
      type: "VibratingScreen",
      status: "grey",
      startTime: "00:20:47",
      lightsConfig: { orientation: "vertical", position: "top" },
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "vibrating_screen_4",
      name: "صفحه 4",
      type: "VibratingScreen",
      status: "blue",
      operatingTime: "05:26:00",
      lightsConfig: { orientation: "vertical", position: "top" },
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "vibrating_screen_5",
      name: "صفحه 5",
      type: "VibratingScreen",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "top" },
      operatingTime: "05:14:00",
      defaultParams: {
        current: "43A",
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "vibrating_screen_6",
      name: "صفحه 6",
      type: "VibratingScreen",
      status: "grey",
      startTime: "10:20:47",
      lightsConfig: { orientation: "vertical", position: "top" },
      defaultParams: {
        current: getRandomCurrent(),
        temperature: getRandomTemperature(),
      },
    },
    {
      id: "granule_sillo_1",
      type: "GranuleSillo",
      name: "سیلو 1",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      operatingTime: "02:45:00",
      defaultParams: {
        soilSurface: getRandomSoilSurface(),
      },
    },
    {
      id: "granule_sillo_2",
      name: "سیلو 2",
      type: "GranuleSillo",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      operatingTime: "04:17:00",
      defaultParams: {
        soilSurface: getRandomSoilSurface(),
      },
    },
    {
      id: "granule_sillo_3",
      name: "سیلو 3",
      type: "GranuleSillo",
      status: "blue",
      lightsConfig: { orientation: "vertical", position: "left" },
      operatingTime: "06:04:00",
      defaultParams: {
        soilSurface: getRandomSoilSurface(),
      },
    },
    {
      id: "granule_sillo_4",
      name: "سیلو 4",
      type: "GranuleSillo",
      status: "none",
      lightsConfig: { orientation: "vertical", position: "left" },
      defaultParams: {
        soilSurface: getRandomSoilSurface(),
      },
    },
    {
      id: "granule_sillo_5",
      name: "سیلو 5",
      type: "GranuleSillo",
      status: "none",
      lightsConfig: { orientation: "vertical", position: "left" },
      defaultParams: {
        soilSurface: getRandomSoilSurface(),
      },
    },
    {
      id: "granule_sillo_6",
      name: "سیلو 6",
      type: "GranuleSillo",
      status: "none",
      lightsConfig: { orientation: "vertical", position: "left" },
      defaultParams: {
        soilSurface: "",
      },
    },
    {
      id: "granule_sillo_7",
      name: "سیلو 7",
      type: "GranuleSillo",
      status: "red",
      startTime: "01:00:48",
      lightsConfig: { orientation: "vertical", position: "right" },
      defaultParams: {
        soilSurface: getRandomSoilSurface(),
      },
    },
    {
      id: "granule_sillo_8",
      name: "سیلو 8",
      type: "GranuleSillo",
      status: "red",
      startTime: "00:50:10",
      lightsConfig: { orientation: "vertical", position: "right" },
      defaultParams: {
        soilSurface: getRandomSoilSurface(),
      },
    },
    {
      id: "granule_sillo_9",
      name: "سیلو 9",
      type: "GranuleSillo",
      status: "red",
      startTime: "08:18:17",
      lightsConfig: { orientation: "vertical", position: "right" },
      defaultParams: {
        soilSurface: getRandomSoilSurface(),
      },
    },
    {
      id: "granule_sillo_10",
      name: "سیلو 10",
      type: "GranuleSillo",
      status: "red",
      startTime: "03:00:50",
      lightsConfig: { orientation: "vertical", position: "right" },
      defaultParams: {
        soilSurface: getRandomSoilSurface(),
      },
    },
    {
      id: "granule_sillo_11",
      name: "سیلو 11",
      type: "GranuleSillo",
      status: "grey",
      startTime: "03:50:07",
      lightsConfig: { orientation: "vertical", position: "right" },
      defaultParams: {
        soilSurface: getRandomSoilSurface(),
      },
    },
    {
      id: "granule_sillo_12",
      name: "سیلو 12",
      type: "GranuleSillo",
      status: "none",
      lightsConfig: { orientation: "vertical", position: "right" },
      defaultParams: {
        soilSurface: getRandomSoilSurface(),
      },
    },
  ],
};
