import { Alarm } from "@/interfaces/admin/alarm";

export const columns = () => [
    {
        id: "id",
        label: "شناسه",
        showOnTable: false,
        canEdit: false,
        isAdditionalAction: false,
    },
    {
        id: "name",
        label: "نام",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "function_info",
        label: "تابع",
        required: true,
        showOnTable: true,
        optionsKey: "functionList",
        isSingleSelect: true,
        canEdit: true,
        isAdditionalAction: false,
        render: (row: Alarm) => row?.function_info?.name || "نامشخص",
    },
    {
        id: "device_info",
        label: "دستگاه",
        required: true,
        showOnTable: true,
        optionsKey: "deviceList",
        isSingleSelect: true,
        canEdit: true,
        isAdditionalAction: false,
        render: (row: Alarm) => row?.device_info?.name || "نامشخص",
    },
    {
        id: "type_info",
        label: "نوع",
        required: true,
        showOnTable: true,
        optionsKey: "dataTypeList",
        isSingleSelect: true,
        canEdit: true,
        isAdditionalAction: false,
        render: (row: Alarm) => row?.type_info?.name || "نامشخص",
    },
    {
        id: "description",
        label: "توضیحات",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "message_type",
        label: "نوع پیغام",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "message",
        label: "متن پیغام",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "receiver_info",
        label: "اطلاعات گیرنده",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "actions",
        label: "عملیات",
        isActionColumn: true,
        canEdit: false,
        isAdditionalAction: false,
    },
];
