export const columns = () => [
    {
        id: "id",
        label: "شناسه",
        showOnTable: false,
        canEdit: false,
        isAdditionalAction: false,
    },
    {
        id: "name",
        label: "نام",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "function",
        label: "تابع",
        required: true,
        showOnTable: true,
        optionsKey: "functionList",
        isSingleSelect: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "device",
        label: "دستگاه",
        required: true,
        showOnTable: true,
        optionsKey: "deviceList",
        isSingleSelect: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "type",
        label: "نوع",
        required: true,
        showOnTable: true,
        optionsKey: "dataTypeList",
        isSingleSelect: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "description",
        label: "توضیحات",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "actions",
        label: "عملیات",
        isActionColumn: true,
        canEdit: false,
        isAdditionalAction: false,
    },
];
