export const columns = () => [
    {
        id: "id",
        label: "شناسه",
        showOnTable: false,
        canEdit: false,
        isAdditionalAction: false,
    },
    {
        id: "first_name",
        label: "نام",
        required: false,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "last_name",
        label: "نام خانوادگی",
        required: false,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "username",
        label: "نام کاربری",
        showOnTable: true,
        required: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "profile_image",
        label: "عکس پروفایل",
        showOnTable: false,
        required: false,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "phone_number",
        label: "شماره موبایل",
        showOnTable: true,
        required: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "email",
        label: "ایمیل",
        isActionColumn: false,
        showOnTable: false,
        required: false,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "is_active",
        label: "وضعیت",
        required: true,
        showOnTable: false,
        isActionColumn: false,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "actions",
        label: "عملیات",
        isActionColumn: true,
        canEdit: false,
        isAdditionalAction: false,
    },
];
