export const columns = () => [
  {
    id: "id",
    label: "شناسه",
    showOnTable: false,
    canEdit: false,
    isAdditionalAction: false,
  },
  {
    id: "user",
    label: "کاربر",
    showOnTable: true,
    required: true,
    canEdit: false,
    isAdditionalAction: false,
  },
  {
    id: "company",
    label: "شرکت",
    showOnTable: true,
    canEdit: true,
    isAdditionalAction: false,
  },
  {
    id: "groups",
    label: "گروه ها",
    showOnTable: true,
    required: false,
    isMultiSelect: true,
    optionsKey: "groupList",
    canEdit: true,
    isAdditionalAction: false,
  },
  {
    id: "permissions",
    label: "دسترسی ها",
    showOnTable: true,
    optionsKey: "permissionList",
    required: false,
    isMultiSelect: true,
    canEdit: true,
    isAdditionalAction: false,
  },
  {
    id: "actions",
    label: "عملیات",
    isActionColumn: true,
    canEdit: false,
    isAdditionalAction: false,
  },
];
