export const columns = () => [
    {
        id: "icon",
        label: "آیکون",
        required: false,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
        isIconSelect: true, 
        optionsKey: "iconList",
    },
    {
        id: "id",
        label: "شناسه",
        showOnTable: false,
        canEdit: false,
        isAdditionalAction: false,
    },
    {
        id: "company",
        label: "شرکت",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
        optionsKey: "companyList",
        isSingleSelect: true,
    },
    {
        id: "name",
        label: "نام",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "code",
        label: "کد",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "actions",
        label: "عملیات",
        isActionColumn: true,
        canEdit: false,
        isAdditionalAction: false,
    },
];
