import { TitlesColumnsData } from "@/interfaces/admin/general";
import { ProductLine } from "@/interfaces/admin/productLine";

export const columns = (): TitlesColumnsData[] => [
    {
        id: "light_icon",
        label: "آیکون تم لایت",
        required: false,
        isImage: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
        isIconSelect: true, 
        optionsKey: "iconList",
    },
    {
        id: "dark_icon",
        label: "آیکون تم دارک",
        required: false,
        isImage: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
        isIconSelect: true, 
        optionsKey: "iconList",
    },
    {
        id: "id",
        label: "شناسه",
        showOnTable: false,
        canEdit: false,
        isAdditionalAction: false,
    },
    {
        id: "company",
        label: "شرکت",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
        optionsKey: "companyList",
        isSingleSelect: true,
        render: (row: ProductLine) => row?.company?.name || "نامشخص",
    },
    {
        id: "name",
        label: "نام",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "code",
        label: "کد",
        required: true,
        showOnTable: false,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "actions",
        label: "عملیات",
        isActionColumn: true,
        canEdit: false,
        isAdditionalAction: false,
    },
];
