export const columns = () => [
    {
        id: "name",
        label: "نام",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "id",
        label: "شناسه",
        showOnTable: false,
        canEdit: false,
        isAdditionalAction: false,
    },
    {
        id: "product_line_part",
        label: "خط تولید جزئی",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
        optionsKey: "productLinePartList",
        isSingleSelect: true,
    },
    {
        id: "data_type",
        label: "نوع داده",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
        optionsKey: "dataTypeList",
        isMultiSelect: true,
    },
    {
        id: "code",
        label: "کد",
        required: true,
        showOnTable: false,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "on_off_identifier",
        label: "مشخص کننده خاموشی",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
        optionsKey: "dataTypeList",
        isSingleSelect: true,
    },
    {
        id: "value",
        label: "مقدار مشخص کننده خاموشی",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "actions",
        label: "عملیات",
        isActionColumn: true,
        canEdit: false,
        isAdditionalAction: false,
    },
];
