import { Container } from "@mui/material";
import ChartTabs from "./live/ChartTabs";


const testDate = {
  data: [
    {
      device_name: "post2",
      device_id: 1,
      device_name_fa: "پست 1",
      allowed_data: {
        phase1_current: "جریان فاز 1",
        phase2_current: "جریان فاز 2",
        phase3_current: "جریان فاز 3", 
        middle_current: "جریان متوسط",
        middle_voltage: "ولتاژ متوسط",
        active_power: "توان اکتیو",
        apparent_power: "توان ظاهری",
        active_energy_delivered: "انرژی فعال تحویلی",
        power_factor: "ضریب توان",
      },
      data: [
        {
          time: 1721500988777,
          phase1_current: 17,
          phase2_current: 70,
          phase3_current: 15,
          middle_current: 80,
          middle_voltage: 518,
          active_power: 123,
          apparent_power: 14,
          active_energy_delivered: 25,
          power_factor: 98,
        },
      ],
    },
    {
      device_name: "post2",
      device_id: 2,
      device_name_fa: "پست 2",
      allowed_data: {
        phase1_current: "جریان فاز 1",
        phase2_current: "جریان فاز 2",
        phase3_current: "جریان فاز 3", 
        middle_current: "جریان متوسط",
        middle_voltage: "ولتاژ متوسط",
        active_power: "توان اکتیو",
        apparent_power: "توان ظاهری",
        active_energy_delivered: "انرژی فعال تحویلی",
        power_factor: "ضریب توان",
      },
      data: [
        {
          time: 17215009800,
          phase1_current: 11,
          phase2_current: 70,
          phase3_current: 15,
          middle_current: 80,
          middle_voltage: 518,
          active_power: 123,
          apparent_power: 14,
          active_energy_delivered: 25,
          power_factor: 98,
        },
      ],
    },
    {
      device_name: "post3",
      device_id: 3,
      device_name_fa: "پست 3",
      allowed_data: {
        phase1_current: "جریان فاز 1",
        phase2_current: "جریان فاز 2",
        phase3_current: "جریان فاز 3", 
        middle_current: "جریان متوسط",
        middle_voltage: "ولتاژ متوسط",
        active_power: "توان اکتیو",
        apparent_power: "توان ظاهری",
        active_energy_delivered: "انرژی فعال تحویلی",
        power_factor: "ضریب توان",
      },
      data: [
        {
          time: 172150000,
          phase1_current: 19,
          phase2_current: 70,
          phase3_current: 15,
          middle_current: 80,
          middle_voltage: 519,
          active_power: 123,
          apparent_power: 14,
          active_energy_delivered: 25,
          power_factor: 98,
        },
      ],
    },
    {
      device_name: "post4",
      device_id: 4,
      device_name_fa: "پست 4",
      allowed_data: {
        phase1_current: "جریان فاز 1",
        phase2_current: "جریان فاز 2",
        phase3_current: "جریان فاز 3", 
        middle_current: "جریان متوسط",
        middle_voltage: "ولتاژ متوسط",
        active_power: "توان اکتیو",
        apparent_power: "توان ظاهری",
        active_energy_delivered: "انرژی فعال تحویلی",
        power_factor: "ضریب توان",
      },
      data: [
        {
          time: 172150001,
          phase1_current: 20,
          phase2_current: 70,
          phase3_current: 15,
          middle_current: 80,
          middle_voltage: 520,
          active_power: 123,
          apparent_power: 14,
          active_energy_delivered: 25,
          power_factor: 98,
        },
      ],
    },
    {
      device_name: "post2",
      device_id: 5,
      device_name_fa: "پست 1",
      allowed_data: {
        phase1_current: "جریان فاز 1",
        phase2_current: "جریان فاز 2",
        phase3_current: "جریان فاز 3", 
        middle_current: "جریان متوسط",
        middle_voltage: "ولتاژ متوسط",
        active_power: "توان اکتیو",
        apparent_power: "توان ظاهری",
        active_energy_delivered: "انرژی فعال تحویلی",
        power_factor: "ضریب توان",
      },
      data: [
        {
          time: 172150030,
          phase1_current: 21,
          phase2_current: 70,
          phase3_current: 15,
          middle_current: 80,
          middle_voltage: 521,
          active_power: 123,
          apparent_power: 14,
          active_energy_delivered: 25,
          power_factor: 98,
        },
      ],
    },
    {
      device_name: "post2",
      device_id: 6,
      device_name_fa: "پست 2",
      allowed_data: {
        phase1_current: "جریان فاز 1",
        phase2_current: "جریان فاز 2",
        phase3_current: "جریان فاز 3", 
        middle_current: "جریان متوسط",
        middle_voltage: "ولتاژ متوسط",
        active_power: "توان اکتیو",
        apparent_power: "توان ظاهری",
        active_energy_delivered: "انرژی فعال تحویلی",
        power_factor: "ضریب توان",
      },
      data: [
        {
          time: 172150098,
          phase1_current: 11,
          phase2_current: 70,
          phase3_current: 15,
          middle_current: 80,
          middle_voltage: 511,
          active_power: 123,
          apparent_power: 14,
          active_energy_delivered: 25,
          power_factor: 98,
        },
      ],
    },
    {
      device_name: "post3",
      device_id: 7,
      device_name_fa: "پست 3",
      allowed_data: {
        phase1_current: "جریان فاز 1",
        phase2_current: "جریان فاز 2",
        phase3_current: "جریان فاز 3", 
        middle_current: "جریان متوسط",
        middle_voltage: "ولتاژ متوسط",
        active_power: "توان اکتیو",
        apparent_power: "توان ظاهری",
        active_energy_delivered: "انرژی فعال تحویلی",
        power_factor: "ضریب توان",
      },
      data: [
        {
          time: 1721500988,
          phase1_current: 12,
          phase2_current: 70,
          phase3_current: 15,
          middle_current: 80,
          middle_voltage: 513,
          active_power: 123,
          apparent_power: 14,
          active_energy_delivered: 25,
          power_factor: 98,
        },
      ],
    },
    {
      device_name: "post4",
      device_id: 8,
      device_name_fa: "پست 4",
      allowed_data: {
        phase1_current: "جریان فاز 1",
        phase2_current: "جریان فاز 2",
        phase3_current: "جریان فاز 3", 
        middle_current: "جریان متوسط",
        middle_voltage: "ولتاژ متوسط",
        active_power: "توان اکتیو",
        apparent_power: "توان ظاهری",
        active_energy_delivered: "انرژی فعال تحویلی",
        power_factor: "ضریب توان",
      },
      data: [
        {
          time: 17215009887,
          phase1_current: 14,
          phase2_current: 70,
          phase3_current: 15,
          middle_current: 80,
          middle_voltage: 515,
          active_power: 123,
          apparent_power: 14,
          active_energy_delivered: 25,
          power_factor: 98,
        },
      ],
    },
    {
      device_name: "post4",
      device_id: 9,
      device_name_fa: "پست 4",
      allowed_data: {
        phase1_current: "جریان فاز 1",
        phase2_current: "جریان فاز 2",
        phase3_current: "جریان فاز 3", 
        middle_current: "جریان متوسط",
        middle_voltage: "ولتاژ متوسط",
        active_power: "توان اکتیو",
        apparent_power: "توان ظاهری",
        active_energy_delivered: "انرژی فعال تحویلی",
        power_factor: "ضریب توان",
      },
      data: [
        {
          time: 172150098877,
          phase1_current: 17,
          phase2_current: 70,
          phase3_current: 15,
          middle_current: 80,
          middle_voltage: 517,
          active_power: 123,
          apparent_power: 14,
          active_energy_delivered: 25,
          power_factor: 98,
        },
        {
          time: 172150098888,
          phase1_current: 10,
          phase2_current: 7,
          phase3_current: 415,
          middle_current: 856,
          middle_voltage: 5547,
          active_power: 1254,
          apparent_power: 15,
          active_energy_delivered: 525,
          power_factor: 9258,
        },
      ],
    },
  ],
};


const HomePage: React.FC = () => {
  return (
    <Container maxWidth={false}>
      <ChartTabs data={testDate.data} />
    </Container>
  );
};

export default HomePage;