import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const vazir = localFont({
  // 300 to 700 , bold
  src: [
    {
      path: "../../public/fonts/Vazir/Vazir-FD-WOL.woff",
      weight: "500",
    },
    {
      path: "../../public/fonts/Vazir/Vazir-Light-FD-WOL.woff",
      weight: "400",
    },

    {
      path: "../../public/fonts/Vazir/Vazir-Thin-FD-WOL.woff",
      weight: "300",
    },

    {
      path: "../../public/fonts/Vazir/Vazir-Medium-FD-WOL.woff",
      weight: "600",
    },
    {
      path: "../../public/fonts/Vazir/Vazir-Bold-FD-WOL.woff",
      weight: "700",
    },
  ],
  variable: "--font-vazir",
});
import Providers from "@/Providers/Providers";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="fa" dir="rtl" className={`${vazir.variable} font-sans`}>
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>

      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
