import { ProductLinePart } from "@/interfaces/admin/productLinePart";

export const columns = () => [
    {
        id: "light_icon",
        label: "آیکون تم لایت",
        required: false,
        showOnTable: false,
        isImage: true,
        canEdit: true,
        isAdditionalAction: false,
        isIconSelect: true, 
        optionsKey: "iconList",
    },
    {
        id: "dark_icon",
        label: "آیکون تم دارک",
        required: false,
        showOnTable: false,
        isImage: true,
        canEdit: true,
        isAdditionalAction: false,
        isIconSelect: true, 
        optionsKey: "iconList",
    },
    {
        id: "name",
        label: "نام",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "id",
        label: "شناسه",
        showOnTable: false,
        canEdit: false,
        isAdditionalAction: false,
    },
    {
        id: "product_line",
        label: "خط تولید",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
        optionsKey: "productLineList",
        render: (row: ProductLinePart) => row?.product_line?.name || "نامشخص",
        isSingleSelect: true,
    },
    {
        id: "live_type",
        label: "نوع داده لایو",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
        optionsKey: "liveTypeList",
        render: (row: ProductLinePart) => row?.live_type?.name || "نامشخص",
        isSingleSelect: true,
    },
    {
        id: "code",
        label: "کد",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "actions",
        label: "عملیات",
        isActionColumn: true,
        canEdit: false,
        isAdditionalAction: false,
    },
];
