export const columns = () => [
    {
        id: "id",
        label: "شناسه",
        showOnTable: false,
        canEdit: false,
        isAdditionalAction: false,
    },
    {
        id: "to",
        label: "ارسال شده برای",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "message",
        label: "پیغام",
        required: true,
        showOnTable: true,
        canEdit: true,
        isAdditionalAction: false,
    },
    {
        id: "status",
        label: "وضعیت",
        required: true,
        showOnTable: true,
        canEdit: false,
        isAdditionalAction: false,
    },
    {
        id: "response",
        label: "پاسخ",
        required: true,
        showOnTable: true,
        canEdit: false,
        isAdditionalAction: false,
    },
    {
        id: "created_at",
        label: "تاریخ",
        showOnTable: true,
        canEdit: false,
        required: false,
        isAdditionalAction: false,
    },
    {
        id: "actions",
        label: "عملیات",
        isActionColumn: true,
        canEdit: false,
        isAdditionalAction: false,
    },
];
